server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    active: aggregation
    # active: dev
  data:
    redis:
      host: 192.168.174.128
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.174.128:8848
